# Generated by Django 4.2.3 on 2023-10-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image1', models.ImageField(upload_to='additional_item_images')),
                ('location', models.CharField(max_length=255)),
                ('insurance_type', models.CharField(max_length=255)),
                ('premium_range', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('additional_items', models.CharField(max_length=255)),
                ('image2', models.ImageField(upload_to='additional_item_images')),
            ],
        ),
        migrations.DeleteModel(
            name='InsuranceCompany',
        ),
    ]
