# Generated by Django 4.2.3 on 2023-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0009_alter_jobapplication_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insured_name', models.CharField(max_length=100)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('vin', models.CharField(max_length=17)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_age', models.PositiveIntegerField()),
                ('previous_status', models.CharField(max_length=100)),
                ('agreement', models.BooleanField()),
            ],
        ),
    ]
