# Generated by Django 4.2.3 on 2023-10-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0011_carinsurancepolicy_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinsurancepolicy',
            name='file_upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
