# Generated by Django 4.2.3 on 2023-10-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0013_alter_carinsurancepolicy_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinsurancepolicy',
            name='file_upload',
        ),
    ]
