# Generated by Django 4.2.3 on 2023-10-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0014_remove_carinsurancepolicy_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinsurancepolicy',
            name='phone',
            field=models.CharField(default='0989870208', max_length=10),
        ),
    ]
