# Generated by Django 4.2.3 on 2023-10-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0015_alter_carinsurancepolicy_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vacancy_count',
        ),
    ]
